Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-amd64-vmwarefusion"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"

  config.vm.define "base" do |base|
      base.vm.provision "shell", path: "../../files/base.sh"
  end
end
