Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-amd64-vmwarefusion"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"
  
  # dns plugin
  #config.landrush.enabled = true

  master_ip = "172.16.55.201"
  slave1_ip = "172.16.55.202"

  cluster_name = "hamster"

  config.vm.define "master" do |master|
      hostname = "master1.hamster"

      master.vm.provider :vmware_fusion do |v, override|
        v.vmx["memsize"] = "2048"
      end

      master.vm.provision "shell", path: "../../files/base.sh"
      master.vm.provision "shell", path: "../../files/mesos-master.sh"
      master.vm.provision "shell", inline: "echo zk://#{master_ip}:2181/mesos > /etc/mesos/zk"
      master.vm.provision "shell", inline: "echo #{master_ip} > /etc/mesos-master/ip"
      master.vm.provision "shell", inline: "echo #{cluster_name} > /etc/mesos-master/cluster"
      master.vm.provision "shell", inline: "echo 1 > /etc/zookeeper/conf/myid"
      master.vm.provision "shell", path: "../../files/mesos-master-start.sh"
      #TODO(mikew) will need to set quorum config in multimaster

      master.vm.provision "shell" do |s|
        s.path = "../haaaaaaaack.sh"
        s.args = ["#{master_ip}", "5050"]
      end
      master.vm.provision "shell" do |s|
        s.path = "../haaaaaaaack.sh"
        s.args = ["#{master_ip}", "8080"]
      end

      master.vm.network "forwarded_port", guest: 8080, host: 18080  # marathon
      master.vm.network "forwarded_port", guest: 5050, host: 15050  # mesos-master
      master.vm.network "forwarded_port", guest: 2181, host: 12181  # zk

      master.vm.hostname = hostname
      master.vm.network "private_network", ip: master_ip
      #master.landrush.host "mesos-master", "172.16.55.201"
  end
  config.vm.define "slave1" do |slave1|
      hostname = "slave1.hamster"

      slave1.vm.provider :vmware_fusion do |v, override|
        v.vmx["memsize"] = "4096"
      end

      slave1.vm.provision "shell", path: "../../files/base.sh"
      slave1.vm.provision "shell", path: "../../files/mesos-slave.sh"
      slave1.vm.provision "shell", inline: "echo zk://#{master_ip}:2181/mesos > /etc/mesos/zk"
      slave1.vm.provision "shell", inline: "echo #{slave1_ip} > /etc/mesos-slave/ip"
      slave1.vm.provision "shell", path: "../../files/mesos-slave-start.sh"
      slave1.vm.provision "shell" do |s|
        s.path = "../haaaaaaaack.sh"
        s.args = ["#{master_ip}", "5051"]
      end

      #slave1.vm.network "forwarded_port", guest: 8080, host: 28080  # marathon
      slave1.vm.network "forwarded_port", guest: 5051, host: 25051  # mesos-slave
      slave1.vm.network "forwarded_port", guest: 2181, host: 22181  # zk

      slave1.vm.hostname = hostname
      slave1.vm.network "private_network", ip: slave1_ip
      #slave1.landrush.host "mesos-slave1", "172.16.55.202"
    end
end
