Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-amd64-vmwarefusion"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"
  
  # dns plugin
  #config.landrush.enabled = true

  master_ip = "172.16.55.211"

  cluster_name = "hamster"

  config.vm.define "combined1" do |combined1|
      hostname = "masterslave.hamster"

      combined1.vm.provider :vmware_fusion do |v, override|
        v.vmx["memsize"] = "4096"
      end

      combined1.vm.provision "shell", path: "../files/base.sh"
      combined1.vm.provision "shell", path: "../files/mesos-combined.sh"
      combined1.vm.provision "shell", inline: "echo zk://#{master_ip}:2181/mesos > /etc/mesos/zk"
      combined1.vm.provision "shell", inline: "echo #{master_ip} > /etc/mesos-master/ip"
      combined1.vm.provision "shell", inline: "echo #{master_ip} > /etc/mesos-slave/ip"
      combined1.vm.provision "shell", inline: "echo #{cluster_name} > /etc/mesos-master/cluster"
      combined1.vm.provision "shell", inline: "echo 1 > /etc/zookeeper/conf/myid"
      combined1.vm.provision "shell", path: "../files/mesos-combined-start.sh"

      combined1.vm.provision "shell" do |s|
        s.path = "./haaaaaaaack.sh"
        s.args = ["#{master_ip}", "5050"]
      end
      combined1.vm.provision "shell" do |s|
        s.path = "./haaaaaaaack.sh"
        s.args = ["#{master_ip}", "8080"]
      end
      combined1.vm.provision "shell" do |s|
        s.path = "./haaaaaaaack.sh"
        s.args = ["#{master_ip}", "5051"]
      end

      combined1.vm.network "forwarded_port", guest: 8080, host: 18080  # marathon
      combined1.vm.network "forwarded_port", guest: 5050, host: 15050  # mesos-master
      combined1.vm.network "forwarded_port", guest: 5051, host: 15051  # mesos-master
      combined1.vm.network "forwarded_port", guest: 2181, host: 12181  # zk

      combined1.vm.hostname = hostname
      combined1.vm.network "private_network", ip: master_ip
      #master.landrush.host "mesos-master", "172.16.55.201"
  end
end
